#!/usr/bin/env node
var app = require('flatiron').app;
app.config.defaults({
  hello: 'aloha'
});
app.use(require('flatiron').plugins.http);
app.use(require('../'));
var port = process.env.PORT || 9099;
app.start(port);
console.log('Example configuration server is listening on port', port);
